BOOTLOADER      = atmel-dfu
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
LTO_ENABLE      = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes


SPLIT_KEYBOARD = yes

