name: nightly build

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: update master
              run: |
                  git config --global user.name 'Nyikos Zoltán'
                  git config --global user.email 'nyikoszoltan0@gmail.com'
                  git remote add upstream https://github.com/qmk/qmk_firmware
                  git fetch upstream
                  git merge upstream/master
                  git push
